name: app_settings_type
attributes:
  - attribute: setting_name
    type: varchar
    varchar_length: '100'
    tsType: string
    unique: true
  - attribute: description
    type: text
    tsType: string
    not_null: false
relationships: []
