name: bot_charging_settings
attributes:
  - attribute: day of week
    type: varchar
    varchar_length: '255'
    tsType: string
    not_null: false
  - attribute: all day
    type: boolean
    tsType: boolean
    not_null: false
  - attribute: start time
    type: timestamp
    tsType: Date
    not_null: true
  - attribute: end time
    type: timestamp
    tsType: Date
    not_null: true
relationships:
  - entity: bot
    eager: false
    not_null: true
