name: universal_app_settings
attributes:
  - attribute: setting_value
    type: varchar
    varchar_length: '255'
    tsType: string
    unique: true
    not_null: true
relationships:
  - entity: app_settings_type
    eager: true
    not_null: true
